easy_admin:
    entities:
        OrderList:
            class: App\Entity\OrderList
        MoneyTransaction:
            class: App\Entity\MoneyTransaction
        Cart:
            class: App\Entity\Order
        Check:
            class: App\Entity\Check
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - name
                    - brand
                    - cost
                    - category
                    - typeSale
                    - description
                    - { property: 'imageFile', type: 'vich_image' }
            list:
                fields:
                    - id
                    - name
                    - brand
                    - cost
                    - category
                    - typeSale
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

